apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: testnexusgo0210d-gitops
  description: This is GitOps manifest for testnexusgo0210d   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: testnexusgo0210d
    backstage.io/kubernetes-id: testnexusgo0210d 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: testnexusgo0210d   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:testnexusgo0210d
