apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: testnexusgo0210d
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testnexusgo0210d 
  name: testnexusgo0210d
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: testnexusgo0210d 
